### ISSUE TITLE
osvr kinect without headset ?

### ISSUE THREAD

**Issue by kennyclaude** [simlrh/OSVR-Kinect#10]
hi steve please can you tell me if it is possible to get osvr server working without acually owning a headset, would it be possible to get it working on flat monitor  without going through the headset driver installation ?
 maybe in conjunction with steamvr nulld-driver which outputs to a monitor bypassing the need of a headset..
does OSVR possess such a capacity ?
the idea is stream to a phone not possessing a capacity to be an OSVR client but nonetheless with kinect fusion + openhmd + osvr kinect (+opentrack) getting all the tracking needed etc..
is it possible theoretically to pull such a feat ?
i mean having a prior knowledge of VR next to zero i have  done a lot of research in this sense and i think that i have indentified every technical way there is to this date and i have to admit that your work is pretty impressive!!
OSVR is a tough one and i know that i can spend a lot of time trying to achieve something that i don't even know is technically possible..

so please sir there is nobody better suited than you to answer this question thx in advance :)
ps: i am also interested in unity 3d.. and just to add that Google-wise there is no discussion giving any clues about this..

**Comment by simlrh** [comment]
Yes, it works fine without a headset.

How you do this depends on what kind of phone you have. It would likely be easier to use Trinus or RiftCat rather than OSVR.

**Comment by kennyclaude** [comment]
i own a 6" screen windows phone so no trinus or riftcat or the likes,
my question is would it be still possible to have osvr video feed say steamvr content in a window on my monitor even without owning any headset alongside some kind of tracking ? (i have kinect+psmove+pseye)

i was hoping that you could explain how that hardware setup and software pipeline would be..
just in a few lines i just asking if it can be done thx :)

**Comment by simlrh** [comment]
Yup, if you don't have a headset it just shows up on the screen, you don't need to set it up
