### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by bridger35** [simlrh/OSVR-Kinect#12]
I need help with the whole processes of doing this, I'm a noob and need guidance on what to do.

**Comment by bridger35** [comment]
I got some of it to work but was greeted with this any suggestions?
 Using config file 'osvr_config_HDK_2_default.json'.
Jan 11 18:54:32.653 info [OSVR Server]: Constructing server as configured...
Jan 11 18:54:32.657 info [OSVR Server]: Loading auto-loadable plugins...
Jan 11 18:54:32.666 info [OSVR Server]: Loading plugins...
Jan 11 18:54:32.666 info [OSVR Server]: Instantiating configured drivers...
Could not access the tracking camera, skipping video-based tracking!

**Comment by simlrh** [comment]
Bug tracker not a support forum. Try the OSVR subreddit
