### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by AArchAngel** [simlrh/OSVR-Kinect#3]
Hi, Awesome work on the plugin have finally got this set up and working but when OSVR server launches the plugin I'm seeing 98% cpu utilisation mostly from OSVR server.

My pc isn't top top spec but I have an I5 3570K and am running a 1060 with 16gb I would expect it to at least handle it. is this normal or is it something I've done setting it up?

**Comment by simlrh** [comment]
It's normal as far as I can tell. I might try experimenting with making it a synchronous plugin but at the moment my diagnosis is: calculating skeletons from depth data is complicated, yall.

**Comment by godbyk** [comment]
@AArchAngel To reduce CPU usage, you could set `"sleep": 1` in the OSVR server config file. This tells the server to sleep for 1 millisecond each loop (it defaults to `0` on Windows).

The potential downside is that it slightly reduces the responsiveness of the server: clients (games) won't get HMD pose updates quite as quickly, etc.

But it's something that's easy to try. If it reduces CPU usage and doesn't degrade performance too much then it's a worthwhile tradeoff.

**Comment by AArchAngel** [comment]
Thanks ill give it a try
