### ISSUE TITLE
Plugin doesnt work with Leap Motion SteamVR driver

### ISSUE THREAD

**Issue by dermarder** [simlrh/OSVR-Kinect#4]
Hello,
first of all thank you very much for this plugin!
Unfortunately im having problems to use the kinect plugin in combination with the Leap Motion SteamVR driver. The Vive controllers are akwys stuttering and it seems that the Kinect plugin and the Leap Driver are trying to set the Controller position at the same time.

Is it possible to deactivate the Position and orientation Tracking of the Hands by Kinect so it is only used for the Head Tracking and the SteamVR drivers can work as they should?

Any help would be awesome.

**Comment by simlrh** [comment]
Hi dermarder,

If you go into the aliases in your osvr_server_config.json and set something like:

    "/me/hands/left": "",
    "/me/hands/right": ""

It should ignore the Kinect input (hopefully OSVR won't mind that you set those values to nothing).

**Comment by dermarder** [comment]
Thank you very much for your help. I figured out that the problem was caused due to other things but not your plugin. (Im very new to OSVR, bought mine last week)
I dont even know how i was able to fix it. I just reinstalled different OSVR versions and after hours of trying, it just worked.

Thanks anyways, have a good day!
