### ISSUE TITLE
reversed axis

### ISSUE THREAD

**Issue by dinoa468** [simlrh/OSVR-Kinect#6]
I have tried V1 and V2 and have the same issue with both. The Tracker view shows everything fine, but when I launch Steam VR, the forward/back and left/right are reversed. As in, moving left and right moves forward and back in the headset, and moving forward and back results in left and right movement. I have tried using the "recenter" button on the Kinect popup, as well as the reset_yaw that is provided with OSVR.

**Comment by simlrh** [comment]
Have you tried the reset yaw command under Tracker alignment in the [docs](https://github.com/simlrh/OSVR-fusion)?

**Comment by dinoa468** [comment]
You can disregard this issue. I was trying the reset yaw, but not via command line as instructed by OSVR Fusion. Using the command line corrects the problem. Thanks!

**Comment by simlrh** [comment]
No problem. Fusion should really do that reset on it's own but I don't have the time!
